# Generated by Django 3.0 on 2023-11-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie/image')),
            ],
        ),
    ]
